
package com.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TrainingPortal_UserSoap", targetNamespace = "http://my.netgear.com/NetgearWS/TrainingPortal_User")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TrainingPortalUserSoap {


    /**
     * 
     * @param paramPassword
     * @param paramUsername
     * @return
     *     returns com.wsclient.Users
     */
    @WebMethod(operationName = "login_validation", action = "http://my.netgear.com/NetgearWS/TrainingPortal_User/login_validation")
    @WebResult(name = "login_validationResult", targetNamespace = "http://my.netgear.com/NetgearWS/TrainingPortal_User")
    @RequestWrapper(localName = "login_validation", targetNamespace = "http://my.netgear.com/NetgearWS/TrainingPortal_User", className = "com.wsclient.LoginValidation")
    @ResponseWrapper(localName = "login_validationResponse", targetNamespace = "http://my.netgear.com/NetgearWS/TrainingPortal_User", className = "com.wsclient.LoginValidationResponse")
    public Users loginValidation(
        @WebParam(name = "param_username", targetNamespace = "http://my.netgear.com/NetgearWS/TrainingPortal_User")
        String paramUsername,
        @WebParam(name = "param_password", targetNamespace = "http://my.netgear.com/NetgearWS/TrainingPortal_User")
        String paramPassword);

}
